version: "3"

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mydata:/var/lib/mysql
    ports:
      - 9306:3306
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: phpappuser
      MYSQL_PASSWORD: MySQLAzure2017
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  app:
    image: laravel-tasks:1.0.0
    restart: always
    ports:
        - 8000:8080
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:i528IcnlMPCLQ5dKjYI6I1Qeh9HaaDIcNaC19RDAKsY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=sampledb
      - DB_USERNAME=phpappuser
      - DB_PASSWORD=MySQLAzure2017

volumes:
  mydata:
