version: "3.2"

services:

  proxy:
    image: nginx:1.14-alpine
    restart: always
    volumes:
      - ${CODE_PATH}:/srv/www/app
      - ${CODE_PATH}/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  
  app:
    image: ${ACR_REPO}/php-fpm
    restart: always
    volumes:
      - ${CODE_PATH}:/srv/www/app
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
