apiVersion: v1
kind: Service
metadata:
  name: laravel-tasks-svc
  labels:
    name: laravel-tasks
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8888
    targetPort: 80
  selector:
    app: laravel-tasks
